import "server-only";
import { prisma } from "@/lib/prisma";

// Auto-generated the moment a deal is created (see lib/offers.ts's accept
// branch) so the retailer is never stuck waiting on the grower to upload a
// file. Points at this app's own invoice page rather than a static
// document — see /deal/[id]/invoice/page.tsx.
export async function generateInvoiceForDeal(dealId: string) {
  await prisma.deal.update({
    where: { id: dealId },
    data: {
      invoiceUrl: `/deal/${dealId}/invoice`,
      invoiceUploadedAt: new Date(),
      invoiceAutoGenerated: true,
    },
  });
}

// Renders the invoice for whoever is looking at it — same anonymization
// boundary as everywhere else: the viewer's own side is real, the
// counterparty is only ever their anonHandle. Broker/admin see both real.
export async function invoiceDataForViewer(dealId: string, viewerId: string, viewerRole: string) {
  const deal = await prisma.deal.findUnique({
    where: { id: dealId },
    include: {
      seller: { select: { id: true, businessName: true, fullName: true, anonHandle: true } },
      retailer: { select: { id: true, businessName: true, fullName: true, anonHandle: true } },
      thread: { include: { listing: true } },
    },
  });
  if (!deal) return null;

  const isBrokerOrAdmin = viewerRole === "broker" || viewerRole === "admin";
  const isSeller = deal.sellerId === viewerId;
  const isRetailer = deal.retailerId === viewerId;
  if (!isBrokerOrAdmin && !isSeller && !isRetailer) return null;

  const sellerLabel =
    isSeller || isBrokerOrAdmin
      ? deal.seller.businessName ?? deal.seller.fullName
      : deal.seller.anonHandle;
  const retailerLabel =
    isRetailer || isBrokerOrAdmin
      ? deal.retailer.businessName ?? deal.retailer.fullName
      : deal.retailer.anonHandle;

  return {
    dealId: deal.id,
    createdAt: deal.createdAt,
    autoGenerated: deal.invoiceAutoGenerated,
    strainName: deal.thread.listing.strainName,
    category: deal.thread.listing.category,
    unit: deal.thread.listing.unit,
    quantity: deal.finalQuantity,
    pricePerUnit: deal.finalPrice,
    total: Math.round(deal.finalQuantity * deal.finalPrice * 100) / 100,
    terms: deal.finalTerms,
    sellerLabel,
    retailerLabel,
  };
}
