import { ShipmentTimeline } from "@/components/deal/shipment-timeline";
import { ProductDecisionForm } from "@/components/deal/product-decision-form";

type DealShipment = {
  status: string;
  transporter: { businessName: string | null; fullName: string };
  events: { id: string; status: string; note: string | null; createdAt: Date }[];
};

type DealCommission = {
  rate: number;
  payerType: string;
  amount: number | null;
  retailerOwes: number | null;
  status: string;
};

type Deal = {
  id: string;
  invoiceUrl: string | null;
  invoiceAutoGenerated: boolean;
  shipment: DealShipment | null;
  productStatus: string;
  commission: DealCommission | null;
};

type Transporter = { id: string; businessName: string | null; fullName: string; preferredTransporter: boolean };

export function DealPanelRetailer({
  deal,
  listingId,
  transporters,
  acceptInvoiceAction,
  acceptProductAction,
  rejectProductAction,
}: {
  deal: Deal;
  listingId: string;
  transporters: Transporter[];
  acceptInvoiceAction: (formData: FormData) => void;
  acceptProductAction: (formData: FormData) => void;
  rejectProductAction: (formData: FormData) => void;
}) {
  const preferred = transporters.find((t) => t.preferredTransporter);

  return (
    <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-800">
      <h3 className="text-xs font-semibold text-gray-900 dark:text-gray-100 mb-2">Fulfillment</h3>

      {!deal.invoiceUrl && (
        <p className="text-xs text-gray-500 dark:text-gray-400">
          Waiting on the seller to upload an invoice.
        </p>
      )}

      {deal.invoiceUrl && !deal.shipment && (
        <form action={acceptInvoiceAction} className="space-y-2">
          <input type="hidden" name="dealId" value={deal.id} />
          <input type="hidden" name="listingId" value={listingId} />
          <p className="text-xs text-gray-500 dark:text-gray-400">
            <a href={deal.invoiceUrl} target="_blank" className="text-green-700 underline">
              View invoice
            </a>{" "}
            {deal.invoiceAutoGenerated ? "(system-generated)" : "(uploaded by seller)"} — accept it
            and pick a transporter to move the order.
          </p>
          {transporters.length === 0 ? (
            <p className="text-xs text-amber-700 dark:text-amber-400">
              No approved transporters yet — check back once one is on the platform.
            </p>
          ) : (
            <>
              <select
                name="transporterId"
                defaultValue={preferred?.id ?? transporters[0]?.id}
                className="border border-gray-300 dark:border-gray-700 rounded-lg px-2 py-1.5 text-xs bg-transparent"
              >
                {transporters.map((t) => (
                  <option key={t.id} value={t.id}>
                    {t.businessName ?? t.fullName}
                    {t.preferredTransporter ? " (preferred)" : ""}
                  </option>
                ))}
              </select>
              <div>
                <button
                  type="submit"
                  className="bg-green-700 text-white rounded-lg px-3 py-1.5 text-xs font-medium"
                >
                  Accept invoice & set up transport
                </button>
              </div>
            </>
          )}
        </form>
      )}

      {deal.shipment && (
        <ShipmentTimeline
          status={deal.shipment.status}
          events={deal.shipment.events}
          transporterName={deal.shipment.transporter.businessName ?? deal.shipment.transporter.fullName}
        />
      )}

      {deal.shipment?.status === "delivered" && deal.productStatus === "pending" && (
        <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-800">
          <p className="text-xs text-gray-500 dark:text-gray-400 mb-2">
            Delivered — inspect the shipment, then accept or reject it.
          </p>
          <ProductDecisionForm
            dealId={deal.id}
            listingId={listingId}
            acceptAction={acceptProductAction}
            rejectAction={rejectProductAction}
          />
        </div>
      )}

      {deal.productStatus === "accepted" && (
        <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-800">
          <p className="text-xs text-green-700 dark:text-green-400 font-medium">
            You accepted this delivery — the transaction is final.
          </p>
          {deal.commission && deal.commission.retailerOwes != null && deal.commission.retailerOwes > 0 && (
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              Broker commission owed: ${deal.commission.retailerOwes} (
              {deal.commission.status === "paid" ? "paid" : "pending payment"})
            </p>
          )}
        </div>
      )}

      {deal.productStatus === "rejected" && (
        <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-800">
          <p className="text-xs text-red-600 dark:text-red-400 font-medium">
            You rejected this delivery. This needs to be resolved directly with the seller — the
            app doesn't run a refund/return process.
          </p>
        </div>
      )}
    </div>
  );
}
