import { ShipmentTimeline } from "@/components/deal/shipment-timeline";

type DealShipment = {
  status: string;
  transporter: { businessName: string | null; fullName: string };
  events: { id: string; status: string; note: string | null; createdAt: Date }[];
};

type DealCommission = {
  rate: number;
  payerType: string;
  amount: number | null;
  growerOwes: number | null;
  status: string;
};

type Deal = {
  id: string;
  invoiceUrl: string | null;
  invoiceAcceptedAt: Date | null;
  invoiceAutoGenerated: boolean;
  shipment: DealShipment | null;
  productStatus: string;
  commission: DealCommission | null;
};

export function DealPanelSeller({
  deal,
  listingId,
  invoiceAction,
}: {
  deal: Deal;
  listingId: string;
  invoiceAction: (formData: FormData) => void;
}) {
  return (
    <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-800">
      <h3 className="text-xs font-semibold text-gray-900 dark:text-gray-100 mb-2">Fulfillment</h3>

      {deal.invoiceUrl && !deal.shipment && (
        <p className="text-xs text-gray-500 dark:text-gray-400 mb-2">
          {deal.invoiceAutoGenerated ? (
            <>
              A system-generated invoice is ready —{" "}
              <a href={deal.invoiceUrl} target="_blank" className="text-green-700 underline">
                view it
              </a>
              . Waiting on the retailer to accept and pick a transporter.
            </>
          ) : (
            <>
              Your uploaded invoice is on file —{" "}
              <a href={deal.invoiceUrl} target="_blank" className="text-green-700 underline">
                view it
              </a>
              . Waiting on the retailer to accept and pick a transporter.
            </>
          )}
        </p>
      )}

      {!deal.shipment && (
        <form action={invoiceAction} className="space-y-2">
          <input type="hidden" name="dealId" value={deal.id} />
          <input type="hidden" name="listingId" value={listingId} />
          <p className="text-xs text-gray-500 dark:text-gray-400">
            {deal.invoiceAutoGenerated
              ? "Prefer your own invoice instead? Upload it to replace the system-generated one."
              : "Upload a different file to replace your invoice."}
          </p>
          <input
            type="file"
            name="invoice"
            accept="image/*,application/pdf"
            required
            className="text-xs file:mr-3 file:rounded-md file:border-0 file:bg-green-700 file:text-white file:px-3 file:py-1.5 file:text-xs"
          />
          <div>
            <button
              type="submit"
              className="border border-gray-300 dark:border-gray-700 text-gray-700 dark:text-gray-300 rounded-lg px-3 py-1.5 text-xs font-medium"
            >
              Upload my own invoice
            </button>
          </div>
        </form>
      )}

      {deal.shipment && (
        <ShipmentTimeline
          status={deal.shipment.status}
          events={deal.shipment.events}
          transporterName={deal.shipment.transporter.businessName ?? deal.shipment.transporter.fullName}
        />
      )}

      {deal.productStatus === "accepted" && (
        <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-800">
          <p className="text-xs text-green-700 dark:text-green-400 font-medium">
            The retailer accepted delivery — the transaction is final.
          </p>
          {deal.commission && deal.commission.growerOwes != null && deal.commission.growerOwes > 0 && (
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
              Broker commission owed: ${deal.commission.growerOwes} (
              {deal.commission.status === "paid" ? "paid" : "pending payment"})
            </p>
          )}
        </div>
      )}

      {deal.productStatus === "rejected" && (
        <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-800">
          <p className="text-xs text-red-600 dark:text-red-400 font-medium">
            The retailer rejected this delivery. This needs to be resolved directly with them —
            the app doesn't run a refund/return process.
          </p>
        </div>
      )}
    </div>
  );
}
