import { notFound } from "next/navigation";
import { Leaf } from "lucide-react";
import { requireAuth } from "@/lib/dal";
import { invoiceDataForViewer } from "@/lib/invoice";
import { CATEGORY_LABELS, TERMS_LABELS, type Category, type Terms } from "@/lib/constants";

export default async function InvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireAuth();
  const { id } = await params;
  const invoice = await invoiceDataForViewer(id, session.user.id, session.user.role);
  if (!invoice) notFound();

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 py-10 px-4">
      <div className="max-w-lg mx-auto bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-8">
        <div className="flex items-center gap-2 mb-6">
          <div className="w-7 h-7 bg-green-700 rounded-lg flex items-center justify-center">
            <Leaf className="w-3.5 h-3.5 text-white" />
          </div>
          <span className="font-semibold text-sm text-gray-900 dark:text-gray-100">
            MI Cannabis Exchange
          </span>
        </div>

        <div className="flex items-start justify-between mb-6">
          <div>
            <h1 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Invoice</h1>
            <p className="text-xs text-gray-400 mono">Deal {invoice.dealId}</p>
          </div>
          {invoice.autoGenerated && (
            <span className="text-[10px] uppercase tracking-wide bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-400 px-2 py-0.5 rounded-full">
              System-generated
            </span>
          )}
        </div>

        <div className="grid grid-cols-2 gap-4 mb-6 text-sm">
          <div>
            <p className="text-[10px] uppercase tracking-wide text-gray-400 mb-1">From</p>
            <p className="text-gray-900 dark:text-gray-100">{invoice.sellerLabel}</p>
          </div>
          <div>
            <p className="text-[10px] uppercase tracking-wide text-gray-400 mb-1">Bill to</p>
            <p className="text-gray-900 dark:text-gray-100">{invoice.retailerLabel}</p>
          </div>
        </div>

        <table className="w-full text-sm mb-6">
          <thead>
            <tr className="text-left text-[10px] uppercase tracking-wide text-gray-400 border-b border-gray-200 dark:border-gray-800">
              <th className="pb-2 font-medium">Item</th>
              <th className="pb-2 font-medium text-right">Qty</th>
              <th className="pb-2 font-medium text-right">Unit price</th>
              <th className="pb-2 font-medium text-right">Total</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-gray-100 dark:border-gray-800">
              <td className="py-2 text-gray-900 dark:text-gray-100">
                {invoice.strainName}
                <div className="text-[10px] text-gray-400">
                  {CATEGORY_LABELS[invoice.category as Category] ?? invoice.category}
                </div>
              </td>
              <td className="py-2 text-right">
                {invoice.quantity} {invoice.unit}
              </td>
              <td className="py-2 text-right">${invoice.pricePerUnit}</td>
              <td className="py-2 text-right font-medium">${invoice.total}</td>
            </tr>
          </tbody>
        </table>

        <div className="flex justify-between text-sm mb-2">
          <span className="text-gray-500 dark:text-gray-400">Terms</span>
          <span className="text-gray-900 dark:text-gray-100">
            {TERMS_LABELS[invoice.terms as Terms] ?? invoice.terms}
          </span>
        </div>
        <div className="flex justify-between text-base font-semibold border-t border-gray-200 dark:border-gray-800 pt-3 mt-3">
          <span>Total due</span>
          <span className="text-green-700 dark:text-green-400">${invoice.total}</span>
        </div>

        <p className="mt-6 text-[10px] text-gray-400 leading-relaxed">
          This is an operational record inside MI Cannabis Exchange, not a substitute for the
          METRC seed-to-sale manifest a licensed transfer requires.
        </p>
      </div>
    </div>
  );
}
